baseURL = 'https://anyobell.github.io/blog/'
languageCode = 'en-us'
title = 'Constant'
theme = 'chicago7'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  customCSS = ["css/custom.css"]

[[menu.header]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.header]]
  name = "All Posts"
  url = "/posts/"
  weight = 2

[[menu.header]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.header]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.header]]
  name = "Tags"
  url = "/tags/"
  weight = 5